version: "3"
services:
  server:
    image: app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb8:3306/test?useSSL=false
    networks:
      - spring-mysql-net
    depends_on:
      - mysqldb8

  mysqldb8:
    image: mysql
    networks:
      - spring-mysql-net
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

networks:
  spring-mysql-net: